dataset_path: data
seed: 42
num_epoch: 100
data_loader:
  common:
    num_voxel_bins: 15
  train:
    batch_size: 8
    shuffle: true
  test:
    batch_size: 1
    shuffle: false
train:
  no_batch_norm: false
  initial_learning_rate: 0.001
  weight_decay: 0.0001
  epochs: 30
  patience: 10
  lr_patience: 5
  lr_factor: 0.5
  smooth_weight: 0.1
val_split: 0.2
